dis Garage_mods_Auxilium_settings_auto_equip_equipment (no update, see commit notes)
Causing crashing

            ERROR: [EXCEPTION] (scripts/common/Event.py, 47):
                Traceback (most recent call last):
                      File "scripts/common/Event.py", line 45, in call
                      File "mod_Auxilium", line 238, in onGui
                      File "mod_Auxilium", line 315, in InventoryRemoval
                      File "mod_Auxilium", line 278, in RemoveAll
                TypeError: equipOptionalDevice() takes exactly 7 arguments (6 given)