updated Custom_Tank_Skins_USSR_Light_LT_432_T_64, dis since error still present.
ERROR: [ERROR] (scripts/common/items/readers/shared_readers.py, 161): Wrong customization slot ID33000 for scripts/item_defs/vehicles/uk/GB86_Centurion_Action_X.xml