dis Tank_Skin_Packs_TheFalkonetts_UUP
2019-08-28 22:19:54.118: ERROR: [EXCEPTION] (scripts/client/game.py, 194):
Traceback (most recent call last):
  File "scripts/client/game.py", line 124, in init
  File "scripts/common/items/__init__.py", line 282, in init
  File "scripts/common/items/vehicles.py", line 306, in init
  File "scripts/common/items/vehicles.py", line 2704, in vehicle
  File "scripts/common/items/vehicles.py", line 2289, in __init__
  File "scripts/common/items/_xml.py", line 176, in readNonNegativeInt
  File "scripts/common/items/_xml.py", line 165, in readInt
  File "scripts/common/items/_xml.py", line 79, in raiseWrongSection
  File "scripts/common/items/_xml.py", line 75, in raiseWrongXml
SoftException: error in 'scripts/item_defs/vehicles/usa/A11_T29.xml': subsection 'emblems/default' is missing or wrong